import ButtonGradient from "./design/svg/ButtonGradient";

import { Viewport } from "next";
import { Sora } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Brain Wave",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  themeColor: "dark",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Header />
        {children}
        <Footer />
        <ButtonGradient />
      </body>
    </html>
  );
}
